version: '3.8'

services:
  # ===========================================
  # INFRASTRUCTURE SERVICES
  # ===========================================
  
  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: github-events-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - github-events-network

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: github-events-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # Data retention - 2 hours max
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_CLEANUP_POLICY: delete
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - github-events-network

  # MinIO for Iceberg Storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: github-events-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - github-events-network

  # Initialize MinIO bucket
  minio-init:
    image: minio/mc:latest
    container_name: github-events-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin123;
      mc mb minio/iceberg || true;
      mc policy set public minio/iceberg;
      echo 'MinIO bucket ready';
      "
    networks:
      - github-events-network

  # ===========================================
  # MICROSERVICES
  # ===========================================

  # GitHub Events Producer Service
  github-producer-service:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: github-producer-service
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8001:8001"  # Producer API
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=github-events
      - PRODUCER_API_PORT=8001
      - FETCH_INTERVAL_SECONDS=30
      - MAX_EVENTS_PER_FETCH=100
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./producer:/app
    restart: unless-stopped
    networks:
      - github-events-network

  # Spark Streaming Service (Kafka → Iceberg)
  spark-streaming-service:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-streaming-service
    depends_on:
      kafka:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    ports:
      - "8002:8002"  # Streaming API
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=github-events
      - SPARK_MASTER=local[*]
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin123
      - S3_BUCKET=iceberg
      - ICEBERG_WAREHOUSE_PATH=s3a://iceberg/warehouse
      - CHECKPOINT_LOCATION=s3a://iceberg/checkpoints
      - STREAMING_API_PORT=8002
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin123
      - AWS_REGION=us-east-1
    volumes:
      - ./spark:/app
    restart: unless-stopped
    networks:
      - github-events-network

  # Data Query Service (Iceberg → API)
  data-query-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: data-query-service
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "8003:8003"  # Query API
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8003
      - SPARK_MASTER=local[*]
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin123
      - ICEBERG_WAREHOUSE_PATH=s3a://iceberg/warehouse
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin123
      - AWS_REGION=us-east-1
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - github-events-network

  # Web Dashboard Service
  dashboard-service:
    image: nginx:alpine
    container_name: dashboard-service
    ports:
      - "8080:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
      - ./nginx-microservices.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - data-query-service
    restart: unless-stopped
    networks:
      - github-events-network

  # ===========================================
  # MONITORING & MANAGEMENT
  # ===========================================

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: github-events
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - github-events-network

  # Service Registry & Health Check
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "8000:8000"  # Registry API
    environment:
      - REGISTRY_PORT=8000
    volumes:
      - ./service-registry:/app
    depends_on:
      - github-producer-service
      - spark-streaming-service
      - data-query-service
    networks:
      - github-events-network

volumes:
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
  minio-data:
    driver: local

networks:
  github-events-network:
    driver: bridge
    name: github-events-network
